version: "2.1"

services:
  web:
    extends:
      file: docker-compose-base.yml
      service: base
    command: >
      sh -c "git pull &&
      yes | django-admin makemigrations --merge --pythonpath /code --settings cabot.settings -v 3 &&
      django-admin makemigrations --pythonpath /code --settings cabot.settings -v 3 cabot_check_nping &&
      django-admin migrate --pythonpath /code --settings cabot.settings -v 3 &&
      gunicorn cabot.wsgi:application -b 0.0.0.0:5000 --workers=5"
    ports:
      - '127.0.0.1:5000:5000'
    depends_on:
      - postgres
      - rabbitmq
    restart: always

  worker:
    extends:
      file: docker-compose-base.yml
      service: base
    command: >
      celery -A cabot worker
      --hostname=FR-PROXAD-20051003-78.203.46.76
      --queues=celery,FR-PROXAD-20051003-78.203.46.76
    depends_on:
      - web
      - postgres
      - rabbitmq
      - events
    restart: always

  beat:
    extends:
      file: docker-compose-base.yml
      service: base
    command: >
      celery -A cabot beat
      --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      - web
      - postgres
      - rabbitmq
    restart: always

  events:
    extends: 
      file: docker-compose-base.yml
      service: base
    command: >
      celery -A cabot events
      --camera django_celery_monitor.camera.Camera
    depends_on:
      - postgres
      - rabbitmq
    restart: always

  postgres:
    image: postgres:alpine
    volumes:
      - ../data:/var/lib/postgresql/data
    environment:
      - ./conf/production.env
    restart: always
    ports:
      - 25432:5432

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    volumes:
      - ../rabbitmq_data:/var/lib/rabbitmq:rw   
      - ../definitions.json:/opt/definitions.json:ro
      - ../rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro
    ports:
      - '25672:5672'
      - '15672:15672'

volumes:
  data:
