FROM clouetb/builder

RUN git clone https://github.com/clouetb/cabot /code

RUN pip install --no-cache-dir -r requirements-plugins.txt

RUN django-admin collectstatic --pythonpath /code --settings cabot.settings
RUN django-admin compress --pythonpath /code --settings cabot.settings

ENTRYPOINT []
CMD ["/bin/sh"]
